// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXJ9ZG3K2fYw5i01SDaiDV0yue_810WwI',
    appId: '1:601726265396:web:ba2abb34543abce96b8261',
    messagingSenderId: '601726265396',
    projectId: 'whatsapp-flutter-d9e1b',
    authDomain: 'whatsapp-flutter-d9e1b.firebaseapp.com',
    storageBucket: 'whatsapp-flutter-d9e1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6kB5yP3Lau89BpEy6smPRltziKFGmxJI',
    appId: '1:601726265396:android:9c4f3f5a9d65b4676b8261',
    messagingSenderId: '601726265396',
    projectId: 'whatsapp-flutter-d9e1b',
    storageBucket: 'whatsapp-flutter-d9e1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuOJCbN_iHxmLN48jn44jGa3NqJqJYvrM',
    appId: '1:601726265396:ios:8cf1cb870c7824556b8261',
    messagingSenderId: '601726265396',
    projectId: 'whatsapp-flutter-d9e1b',
    storageBucket: 'whatsapp-flutter-d9e1b.appspot.com',
    iosClientId: '601726265396-sdui5677hlr1g2r601jm7trb900ugang.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuOJCbN_iHxmLN48jn44jGa3NqJqJYvrM',
    appId: '1:601726265396:ios:8cf1cb870c7824556b8261',
    messagingSenderId: '601726265396',
    projectId: 'whatsapp-flutter-d9e1b',
    storageBucket: 'whatsapp-flutter-d9e1b.appspot.com',
    iosClientId: '601726265396-sdui5677hlr1g2r601jm7trb900ugang.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
